<a href="https://colab.research.google.com/github/halzihaozhou/MLOPS-zoomcamp/blob/main/01_intro_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import os

In [14]:
folder_path = '/content/drive/MyDrive/MLOPS-zoomcamp/'

In [45]:
parquet_files = sorted(
    [os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith('.parquet')]
)

In [47]:
parquet_files

['/content/drive/MyDrive/MLOPS-zoomcamp/yellow_tripdata_2023-01.parquet',
 '/content/drive/MyDrive/MLOPS-zoomcamp/yellow_tripdata_2023-02.parquet']

In [60]:
df_1 = pd.read_parquet(parquet_files[0])

In [61]:
df_1.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [62]:

df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

In [63]:
df_1['duration'] =df_1['tpep_dropoff_datetime'] - df_1['tpep_pickup_datetime']
df_1['duration'] =df_1['duration'].dt.total_seconds()/60

In [64]:
df_1

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,13.983333
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,19.450000
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,24.516667
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,13.000000
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,14.400000

In [65]:
df_1['duration'].std()

42.594351241920904

In [66]:
df  = df_1[(df_1.duration >= 1) & (df_1.duration <= 60)]

In [69]:
len(df)/len(df_1)

0.9812202822125979

In [92]:
categorical = ['PULocationID', 'DOLocationID']
df[categorical] = df[categorical].astype(str)

<ipython-input-92-a7ebd0342db8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[categorical] = df[categorical].astype(str)

In [93]:
from sklearn.feature_extraction import DictVectorizer

In [94]:
train_dicts = df[categorical].to_dict(orient='records')

In [95]:
dv= DictVectorizer()
x_train= dv.fit_transform(train_dicts)

In [96]:
x_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6018346 stored elements and shape (3009173, 515)>

In [97]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

In [98]:
y_train = df['duration'].values

In [99]:
lr = LinearRegression()
lr.fit(x_train, y_train)
rmse = root_mean_squared_error(y_train, lr.predict(x_train))
rmse

7.649261932106969

In [100]:
# validation dataset  RMSE

df_2 = pd.read_parquet(parquet_files[1])
df_2['duration'] =df_2['tpep_dropoff_datetime'] - df_2['tpep_pickup_datetime']
df_2['duration'] =df_2['duration'].dt.total_seconds()/60
df_new  = df_2[(df_2.duration >= 1) & (df_2.duration <= 60)]
df_new[categorical] = df_new[categorical].astype(str)
val_dicts = df_new[categorical].to_dict(orient='records')
x_val= dv.transform(val_dicts)
y_val = df_new['duration'].values
rmse_val= root_mean_squared_error(y_val, lr.predict(x_val))
rmse_val

<ipython-input-100-b1ae8f8efd28>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[categorical] = df_new[categorical].astype(str)

7.811818743246608